### ISSUE TITLE
Table row sizing bug

### ISSUE THREAD

**Issue by ctrueden** [imagej/imagej-common#27]
There is a bug in the Table implementation, as illustrated by the following code:

``` java
import imagej.data.table.DefaultGenericTable;
import imagej.data.table.GenericTable;

public class TableBug {

    public static void main(final String[] args) throws Exception {
        final String first = "First";
        final String second = "Second";
        final int rowCount = 10;

        final GenericTable table = new DefaultGenericTable();
        table.setRowCount(rowCount);
        table.appendColumn(first);
        table.appendColumn(second);

        for (int row = 0; row < rowCount; row++) {
            table.set(first, row, "1st:" + row);
            table.set(second, row, "2nd:" + row);
        }

        System.out.println(table);
    }

}
```

It throws the following exception:

```
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.ArrayList.RangeCheck(ArrayList.java:547)
    at java.util.ArrayList.set(ArrayList.java:337)
    at imagej.data.table.AbstractTable.set(AbstractTable.java:408)
    at TableBug.main(TableBug.java:18)
```

But if you move the `setRowCount` call after the two `appendColumn` calls, the code works.

Migrated-From: http://trac.imagej.net/ticket/1647

**Comment by ctrueden** [comment]
Since this issue was filed, the Table API moved to https://github.com/scijava/scijava-table. I tried to reproduce this bug by changing the imports to `org.scijava.table` (the API used above is still the same otherwise). But it works now. So closing this issue as presumed fixed!
