### ISSUE TITLE
DefaultPrefService can throw NPE

### ISSUE THREAD

**Issue by ctrueden** [imagej/imagej-common#48]
The following exception can be thrown by the `DefaultPrefService` when persisting values:
```
java.lang.NullPointerException
	at java.util.prefs.AbstractPreferences.put(AbstractPreferences.java:241)
	at org.scijava.prefs.DefaultPrefService.put(DefaultPrefService.java:183)
	at org.scijava.module.DefaultModuleService.save(DefaultModuleService.java:280)
	at org.scijava.module.process.SaveInputsPreprocessor.saveValue(SaveInputsPreprocessor.java:74)
	at org.scijava.module.process.SaveInputsPreprocessor.process(SaveInputsPreprocessor.java:65)
	at org.scijava.module.ModuleRunner.preProcess(ModuleRunner.java:104)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:156)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:126)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:65)
	at org.scijava.thread.DefaultThreadService$2.call(DefaultThreadService.java:164)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
To reproduce, open the `SingleInputPreprocessorTest`, remove the `persist = false` attribute from the `private T thing` parameter of `HasASingleInput`, and run the tests.

**Comment by ctrueden** [comment]
This is probably a SciJava Common bug, but the `SingleInputPreprocessorTest` provides an easy way to reproduce, and that class lives in ImageJ Common. *shrug*
