### ISSUE TITLE
AIOOB when creating a dataset with one dimension

### ISSUE THREAD

**Issue by hinerm** [imagej/imagej-common#49]
Illustrated in this sample python script:

```
# @OpService ops
# @DisplayService display

blank = ops.createimg(100)

display.createDisplay(blank)
```

Which causes the following exception:

```
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at net.imagej.display.DefaultDatasetView.xyPlane(DefaultDatasetView.java:340)
	at net.imagej.display.DefaultDatasetView.autoscale(DefaultDatasetView.java:169)
	at net.imagej.display.DefaultDatasetView.initializeView(DefaultDatasetView.java:515)
	at net.imagej.display.DefaultDatasetView.rebuild(DefaultDatasetView.java:399)
	at net.imagej.display.DefaultImageDisplay.rebuild(DefaultImageDisplay.java:136)
	at net.imagej.display.DefaultImageDisplay.display(DefaultImageDisplay.java:274)
	at org.scijava.display.DefaultDisplayService.createDisplay(DefaultDisplayService.java:221)
	at org.scijava.display.DefaultDisplayService.createDisplay(DefaultDisplayService.java:207)
```

Which makes sense, since there is no "Y" for a y plane.

**Comment by ctrueden** [comment]
Script syntax is slightly different in 2022:
```groovy
#@ OpService ops
#@ DisplayService display
blank = ops.create().img(100)
display.createDisplay(blank)
```
But this bug persists. 😅
