### ISSUE TITLE
ImageDisplayService concurrency issue

### ISSUE THREAD

**Issue by ctrueden** [imagej/imagej-common#70]
```
org.scijava.module.MethodCallException: Error executing method: net.imagej.MorphologicalFilters#previewChanged
	at org.scijava.module.MethodRef.execute(MethodRef.java:74)
	at org.scijava.module.AbstractModuleItem.callback(AbstractModuleItem.java:230)
	at org.scijava.widget.DefaultWidgetModel.callback(DefaultWidgetModel.java:188)
	at org.scijava.widget.DefaultWidgetModel$1.run(DefaultWidgetModel.java:177)
	at org.scijava.thread.DefaultThreadService$2.run(DefaultThreadService.java:221)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.scijava.module.MethodRef.execute(MethodRef.java:70)
	... 9 more
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at net.imagej.display.DefaultImageDisplay.update(DefaultImageDisplay.java:298)
	at net.imagej.MorphologicalFilters.previewChanged(MorphologicalFilters.java:83)
	... 13 more
```

**Comment by ctrueden** [comment]
Ran into this again:
```
org.scijava.module.MethodCallException: Error executing method: kn.uni.bic.ColocalizationInfluences#translationChanged
	at org.scijava.module.MethodRef.execute(MethodRef.java:74)
	at org.scijava.module.AbstractModuleItem.callback(AbstractModuleItem.java:230)
	at org.scijava.widget.DefaultWidgetModel.callback(DefaultWidgetModel.java:188)
	at org.scijava.widget.DefaultWidgetModel$1.run(DefaultWidgetModel.java:177)
	at org.scijava.thread.DefaultThreadService$2.run(DefaultThreadService.java:221)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.scijava.module.MethodRef.execute(MethodRef.java:70)
	... 9 more
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at net.imagej.interval.CombinedRealInterval.update(CombinedRealInterval.java:78)
	at net.imagej.display.DefaultImageDisplay.update(DefaultImageDisplay.java:297)
	at kn.uni.bic.ColocalizationInfluences.translationChanged(ColocalizationInfluences.java:250)
	... 14 more
org.scijava.module.MethodCallException: Error executing method: kn.uni.bic.ColocalizationInfluences#translationChanged
	at org.scijava.module.MethodRef.execute(MethodRef.java:74)
	at org.scijava.module.AbstractModuleItem.callback(AbstractModuleItem.java:230)
	at org.scijava.widget.DefaultWidgetModel.callback(DefaultWidgetModel.java:188)
	at org.scijava.widget.DefaultWidgetModel$1.run(DefaultWidgetModel.java:177)
	at org.scijava.thread.DefaultThreadService$2.run(DefaultThreadService.java:221)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.scijava.module.MethodRef.execute(MethodRef.java:70)
	... 9 more
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at net.imagej.interval.CombinedRealInterval.update(CombinedRealInterval.java:78)
	at net.imagej.display.DefaultImageDisplay.update(DefaultImageDisplay.java:297)
	at kn.uni.bic.ColocalizationInfluences.translationChanged(ColocalizationInfluences.java:250)
	... 14 more
```

@stelfrich and I traced the culprit to `DefaultImageDisplay#onEvent(DataRestructuredEvent)` which spawns a new thread via `ThreadService#run` every time. See imagej/imagej@66dcd5ef2a and imagej/imagej@30dba64434.
