### ISSUE TITLE
Exception creating DefaultImageJUIService

### ISSUE THREAD

**Issue by ctrueden** [imagej/imagej-common#85]
[From](https://gitter.im/scenerygraphics/SciView?at=5d94aeb39d4cf1736057daa6) @skalarproduktraum:

<blockquote>

```
java.lang.IllegalArgumentException: Invalid service: net.imagej.ui.DefaultImageJUIService

    at org.scijava.service.ServiceHelper.createExactService(ServiceHelper.java:281)
    at org.scijava.service.ServiceHelper.loadService(ServiceHelper.java:232)
    at org.scijava.service.ServiceHelper.loadService(ServiceHelper.java:195)
    at org.scijava.service.ServiceHelper.loadServices(ServiceHelper.java:167)
    at org.scijava.Context.<init>(Context.java:281)
    at org.scijava.Context.<init>(Context.java:237)
    at org.scijava.Context.<init>(Context.java:133)
    at org.scijava.Context.<init>(Context.java:120)
    at org.scijava.Context.<init>(Context.java:109)
    at graphics.scenery.repl.REPL.<init>(REPL.kt:33)
    at graphics.scenery.SceneryBase.main(SceneryBase.kt:196)
    at graphics.scenery.tests.examples.basic.SponzaExample.main(SponzaExample.kt:107)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
    at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.scijava.NullContextException: Before attempting to use this object, please set its context by calling the setContext(...) method.
    at org.scijava.AbstractContextual.context(AbstractContextual.java:58)
    at org.scijava.service.Service.registerEventHandlers(Service.java:68)
    at org.scijava.service.ServiceHelper.createServiceRecursively(ServiceHelper.java:355)
    at org.scijava.service.ServiceHelper.createExactService(ServiceHelper.java:270)
    ... 33 more
```

</blockquote>

**Comment by skalarproduktraum** [comment]
I should add this only happens sporadically, without any (recognisable) pattern. The code that creates the REPL in scenery can be provided with an existing context (as in SciView), or it'll just do `new Context()`. This issue happens in both cases.
